engines:
  bundler-audit:
      enabled: false
  csslint:
    enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: false
  phpcodesniffer:
    enabled: false
  phpmd:
    enabled: false
  rubocop:
      enabled: false
ratings:
  paths:
  - Gemfile.lock

exclude_paths:		
- test/**/*		
- app/**/*
- config/**/*
- ".spec.js"

#testing
