# This is a sample .codeclimate.yml configured for Engine analysis on Code
# Climate Platform For an overview of the Code Climate Platform, see here:
# http://docs.codeclimate.com/article/300-the-codeclimate-platform

# Under the engines key, you can configure which engines will analyze your repo.
# Each key is an engine name. For each value, you need to specify enabled: true
# to enable the engine as well as any other engines-specific configuration.

# For more details, see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
  phpcodesniffer:
    enabled: true
  fixme:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
    - app/**
    - libraries/SME/**
    - libraries/RE/**
    - "**.css"
    - **.js
exclude_paths:
  - libraries/PHPExcel/**
  - libraries/phpqrcode**
  - libraries/ZendFramework**
